---
- hosts: all
  sudo: yes
  gather_facts: no
  vars:
    shared: /vagrant

  tasks:
    - name: Download and Install Node v0.12
      shell: wget -qO- https://deb.nodesource.com/setup_0.12 | bash -

    - name: Grabbing the gradle repository
      apt_repository: repo='ppa:cwchien/gradle' state=present

    - name: Ensure apt cache is up to date
      apt: update_cache=yes

    - name: Ensure packages are installed
      apt: name={{item}}
      with_items:
          - vim
          - git
          - openjdk-7-jdk
          - postgresql
          - python-psycopg2
          - gradle
          - build-essential
          - nodejs

    - name: Install Bower Globally
      npm: name=bower global=yes state=present

    - name: Install Gulp Globally
      npm: name=gulp global=yes state=present

    - name: Add aliases to system
      lineinfile:
        dest: /home/vagrant/.bashrc
        line: "{{item}}"
      with_items:
        - alias idp="cd {{shared}} && bower install && npm install"
        - alias rapi="cd {{shared}}/api && gradle tomcatRun"
        - alias rapp="cd {{shared}} && gulp serve"

- hosts: all
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  vars:
    dbname: uaisoccer
    dbuser: uaiadmin
    dbpassword: admin

  tasks:
  - name: Ensure database is created
    postgresql_db: name={{dbname}}

  - name: Ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: Ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
