---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:
    - name: ensure apt cache is up to date
      apt: update_cache=yes

    - name: ensure packages are installed
      apt: name={{item}}
      with_items:
          - postgresql
          - libpq-dev
          - python-psycopg2

- hosts: all
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  vars:
    dbname: uaisoccer
    dbuser: uaiadmin
    dbpassword: admin

  tasks:
  - name: ensure database is created
    postgresql_db: name={{dbname}}

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

  - name: ensure user does not have unnecessary privilege
    postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
