---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:
    - name: Download and Install Node v0.12
      shell: wget -qO- https://deb.nodesource.com/setup_0.12 | bash -

    - name: Grabbing the gradle repository
      apt_repository: repo='ppa:cwchien/gradle' state=present

    - name: Ensure apt cache is up to date
      apt: update_cache=yes

    - name: Ensure packages are installed
      apt: name={{item}}
      with_items:
          - vim
          - git
          - openjdk-7-jdk
          - postgresql
          - python-psycopg2
          - gradle
          - build-essential
          - nodejs

    - name: Install Bower Globally
      npm: name=bower global=yes state=present

    - name: Install Gulp Globally
      npm: name=gulp global=yes state=present

- hosts: all
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  vars:
    dbname: uaisoccer
    dbname_test: uaisoccer_test
    dbuser: uaiadmin
    dbpassword: admin

  tasks:
    - name: Ensure databases are created
      postgresql_db: name={{dbname}}
      postgresql_db: name={{dbname_test}}

    - name: Ensure user has access to databases
      postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
      postgresql_user: db={{dbname_test}} name={{dbuser}} password={{dbpassword}} priv=ALL

    - name: Ensure user does not have unnecessary privilege
      postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

